### ISSUE TITLE
If no response schema available show a fallback in json

### ISSUE THREAD

**Issue by AnthonyMde** [hopfront/hopfront#101]

**Comment by mbouchenoire** [comment]
We can display the response in the "normal" format (not in JSON), it's just that we cannot "smartify" the response (with foreign keys etc).

**Comment by AnthonyMde** [comment]
First fallback implementation feels and looks as a normal response in HopFront excepting the fact that there is no intelligence as mentioned by @mbouchenoire + I added a warning to the user to be explicit that he is seeing a fallback.

Here the visual suggestion (be free to provide feedbacks on the alert and the wordings @remihrt @mbouchenoire @FabienWitick).

![Image](https://github.com/hopfront/hopfront/assets/32137920/87d811a3-012a-46c1-8cd5-2614eaf9cfe9)

**Comment by remihrt** [comment]
Fallback implementation is great.
I wouldn't use pronouns: "~~We are~~ Displaying data without schema as a fallback".

**Comment by AnthonyMde** [comment]
Ok, I will turn the phrase to the passive form like : 
"Data is displayed without schema as a fallback".

**Comment by FabienWitick** [comment]
Is it relevant to display the Schema name when we could not find it?
