### ISSUE TITLE
Manual spec synchronization

### ISSUE THREAD

**Issue by AnthonyMde** [hopfront/hopfront#102]

**Comment by AnthonyMde** [comment]
@remihrt @mbouchenoire @FabienWitick I need more specifications on this ticket. 
What do we want exactly as an MVP version?

1. Go to settings > Select one OpenApi spec imported before > Add a new entry/button in spec's settings "Update my specification"
2. Display and reuse importation component if possible 
3. During the import : 
- replace old spec with new one but conserving the spec id
- keep extension to prevent user configuration lost : do we really need to have a "diff" between old and new extension? New spec elements won't have any extension configuration, and removed endpoints will not use old extension values. I.E extension will keep old stuff not used but it's not a big deal as a first try I guess. 
4. Do we add warnings? Like dashboard using removed endpoints, or we just let the user noticed about it (as he should know in the first place the modification he made) ?

What do you think about it?

**Comment by mbouchenoire** [comment]
I'd say as an MVP we don't do anything to the extension when we update the spec.

We can add a warning :
- If you changed an endpoint _and_ his id, previous configuration will be lost;
- if you changed parameter / property names, they will be lost;
- ?

**Comment by remihrt** [comment]
> 1. Go to settings > Select one OpenApi spec imported before > Add a new entry/button in spec's settings "Update my specification"

Great!

> 2. Display and reuse importation component if possible

Of course.

> 3. During the import :
> 
> * replace old spec with new one but conserving the spec id
> * keep extension to prevent user configuration lost : do we really need to have a "diff" between old and new extension? New spec elements won't have any extension configuration, and removed endpoints will not use old extension values. I.E extension will keep old stuff not used but it's not a big deal as a first try I guess.
> 

I don't get all the technical implications here.

> 4. Do we add warnings? Like dashboard using removed endpoints, or we just let the user noticed about it (as he should know in the first place the modification he made) ?

A generic warning message about what could append is enough.

> What do you think about it?

As a minimum viable feature we should focus on the quickest way to implement it and the other issues will follow.

The first step would be like today when we delete an API and re-import an new spec version but with a better user flow.
