### ISSUE TITLE
Deactivate automatic get in browse

### ISSUE THREAD

**Issue by AnthonyMde** [hopfront/hopfront#103]

**Comment by AnthonyMde** [comment]
@remihrt I'm not sure about this issue. What implementation do we want? 

1. A submit button for each GET ?
2. Trigger GET only when all values are filled + do not preselect default value (for a enum for example).

- Example: I'm on /getByStatus (petstore) > enum is not preselect > as soon as select a type (ex: available) the GET request is fired
- OR : I'm on /getByStatus > enum is selected + I have a submit button > request is never automatically fired

**Comment by FabienWitick** [comment]
@AnthonyMde it is about not running a request when selecting any operation from the Browse list. 

>  I'm on /getByStatus > enum is selected + I have a submit button > request is never automatically fired

Is the right way.

**Comment by FabienWitick** [comment]
Remember to deactivate the automation only for the Browe view
