### ISSUE TITLE
Auto-saving in settings

### ISSUE THREAD

**Issue by remihrt** [hopfront/hopfront#130]
Expected behavior :

- For select, radio button, switch, etc. :
  - Auto-saving is triggered when value changes.
- For input text :
  - Auto-saving is triggered only if value is changed after a delay of inactivity or when the input loses focus.
  - Input don't lose focus if auto-saving is triggered.

**Comment by AnthonyMde** [comment]
This ticket is obsolete since with this issue: #149

**Comment by mbouchenoire** [comment]
> This ticket is obsolete with this issue: https://github.com/hopfront/hopfront/issues/149

Why is it osbolete now?

**Comment by AnthonyMde** [comment]
The problem was linked to static authentification configuration. It does not exist with the access token conf.
