### ISSUE TITLE
Can't perform table item operation

### ISSUE THREAD

**Issue by remihrt** [hopfront/hopfront#162]
I tested #25.

With this configuration when a table item's operation modal appears the page is reloaded.

**Comment by remihrt** [comment]
https://github.com/hopfront/hopfront/assets/2743541/7a170911-5427-494f-bda5-8d96d6dc29fb

**Comment by mbouchenoire** [comment]
Actually I'm not sure how to handle this issue. The problem is that the user has to be redirected to the auth provider (here Keycloak) while being on a modal, because said modal requires an authentication. I don't see how, after authenticating (which happened in the video), we can get back to the modal while keeping its previous state :(.

**Comment by AnthonyMde** [comment]
I think the initial problem was that the current page was reloading without even asking for authentication. 
As I reproduced, authentication worked, but we lose the current request result. 
What can be nice in the first place is to cache the last operation result in cache? User will lose the menu popup but not the whole response. As he needed to authenticate in a difference space it seems quite ok for me.

Other solution is to find a way to open authentication without leaving HopFront. Is it possible to do it in another tab?

**Comment by mbouchenoire** [comment]
> What can be nice in the first place is to cache the last operation result? User will lose the menu popup but not the whole response. As he needed to authenticate in a different space it seems quite ok for me.

It doesn't solve the issue though, it just displaces it.

> Other solution is to find a way to open authentication without leaving HopFront. Is it possible to do it in another tab?

Not possible sadly.

**Comment by AnthonyMde** [comment]
The problem was initially a bug. For me is now more a UX problem than a bug. It's less problematic as it's not a blocking issue anymore and it might need a new specific issue.

> Not possible sadly.

If it's a library limitation, I don't know what we could do but try to ease the process around it.

**Comment by mbouchenoire** [comment]
> The problem was initially a bug. For me is now more a UX problem than a bug. It's less problematic as it's not a blocking issue anymore and it might need a new specific issue.

I don't see how it changes anything really:
- now: you click "submit" then on a row's "more (menu)", then on the action,
- with your proposal: you don't need to click on "submit" anymore, but still on "more", then on the action.

In both cases the user has lost progress in the process, he just needs to click 1 less button (submit).

Also, It's important to note that the issue arises only when the user does not already authenticated with the auth provider or lost his token locally.
