### ISSUE TITLE
Delete relevant dashboard panels when an API is deleted (?)

### ISSUE THREAD

**Issue by mbouchenoire** [hopfront/hopfront#40]

**Comment by AnthonyMde** [comment]
We cannot do it this way or we may remove dashboard using just one panel of an API and delete all others relevant panels.
I think panels and variables should have a "stale" state in that case. So the user can see what is staled and replace or delete it.

**Comment by mbouchenoire** [comment]
I'm going for the "stale" state for panels using a non-existing API (with an explicit message). It's true that we cannot just delete obsolete panels since users may want to just re-configure them to use other APIs for example.
