### ISSUE TITLE
Spec import does not work when spec does not have a title

### ISSUE THREAD

**Issue by mbouchenoire** [hopfront/hopfront#42]

**Comment by AnthonyMde** [comment]
What do we do? 
Keep basing specId on title and ask spec's title to be mandatory?
Or generate a random specId and replace missing title by something else?

**Comment by mbouchenoire** [comment]
> What do we do? Keep basing specId on title and ask spec's title to be mandatory? Or generate a random specId and replace missing title by something else?

I'm currently working on generating an unique identifier at import instead of using the title of the spec. It's been a long time since I wanted to implement this anyway.

**Comment by AnthonyMde** [comment]
Ok we'll have to check if the UI is not buggy without any title. Maybe we can replace it by the import url string?

**Comment by mbouchenoire** [comment]
> Ok we'll have to check if the UI is not buggy without any title. Maybe we can replace it by the import url string?

Done, I've labeled every empty title with "Untitled API".
