### ISSUE TITLE
Crash when trying to add a serie on chart panel configuration

### ISSUE THREAD

**Issue by remihrt** [hopfront/hopfront#57]
<img width="1201" alt="Screenshot 2023-11-20 at 14 46 53" src="https://github.com/hopfront/hopfront/assets/2743541/4591e065-221a-43e8-b799-78363be85d6e">

**Comment by remihrt** [comment]
https://github.com/hopfront/hopfront/assets/2743541/fb6a816b-e279-4cea-acaf-851cfa5be6a0

**Comment by mbouchenoire** [comment]
I also cannot reproduce this issue on the latest version. Can you DM me so we can debug this live?

**Comment by AnthonyMde** [comment]
If it's your last word Jean-Pierre I close

**Comment by FabienWitick** [comment]
I also cannot reproduce this bug.

**Comment by remihrt** [comment]
I found out the cause of the crash.
I manually set `joy-mode` to `system`.
