### ISSUE TITLE
UI broken on "create variable"

### ISSUE THREAD

**Issue by AnthonyMde** [hopfront/hopfront#58]
<img width="1031" alt="image" src="https://github.com/hopfront/hopfront/assets/32137920/7e7d8443-819c-4a91-97e9-b170862032fc">

**Comment by remihrt** [comment]
Could be great to have "Create variable" in a bottom section in the dropdown.  
It would force to see all the variables before creating a new one.

**Comment by AnthonyMde** [comment]
I implemented an intermediary solution: 
If no variable available at all => we show the create variable button.
If one or more variables available => we show the button **only** in the select options.
I kept type's select (variable or constant), it's clearer IMO.

![image](https://github.com/hopfront/hopfront/assets/32137920/4992acfe-33c7-49cb-811c-c098854b2085)
