### ISSUE TITLE
CORS through proxy

### ISSUE THREAD

**Issue by glb-cblin** [hopfront/hopfront#83]
My APIS do not allow CORS

When I setup hopfront (with docker), I'd like the possssiblity to use the server as a proxy (so my browser does GET http://localhost:3000/my-api/my-endpoint and the request is not a CORS because hopfront server will translate /my-api into https://mydomain.com/my-endpoint)

**Comment by AnthonyMde** [comment]
Hello, thank you for your feedback.

If you have CORS issues, you can use HopFront server as a proxy by activating the switch "bypass browser CORS" in settings (or during your onboarding, in the connectivity step).
Activating this switch will send your browser requests like "GET http://my-domain/my-api/my-endpoint" to HopFront server. HopFront server will then make the call to your API (which will still be "GET http://my-domain/my-api/my-endpoint").

If you did activate this option, can you give me more details on what you want to achieve to clarify your request? 

Thank you.

**Comment by glb-cblin** [comment]
Thanks for the answer @AnthonyMde 👍 

I completely missed that option during bootstrap so I retried with it enabled thanks to the configuration

When I use this option, I always have a 500 Internal server error

This is caused by the fact that, my Company root CA is not activated inside the docker and so hopfront consider it unsafe
Is there an option (like an env var) to ignore self signed certificates ?
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: self-signed certificate in certificate chain
      at TLSSocket.onConnectSecure (node:_tls_wrap:1600:34)
      at TLSSocket.emit (node:events:517:28)
      at TLSSocket._finishInit (node:_tls_wrap:1017:8)
      at ssl.onhandshakedone (node:_tls_wrap:803:12)
      at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'SELF_SIGNED_CERT_IN_CHAIN'
```

**Comment by glb-cblin** [comment]
Ok, I've found a way : `docker run -p 3000:3000 -v hopfront:/etc/hopfront -e NODE_TLS_REJECT_UNAUTHORIZED="0" hopfront/hopfront:latest`
