### ISSUE TITLE
Couldn't find schema for response object

### ISSUE THREAD

**Issue by glb-cblin** [hopfront/hopfront#84]
I have an open api document with

```
"/system": {
      "get": {
        "tags": [
          "System"
        ],
        "summary": "Retrieves public data about the system",
        "operationId": "GetSystemInformation",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SystemInformation"
                }
              }
            }
          }
        }
      }
    },
```

and SystemInformation exists later in the spec

However, when I try to see it in hopfront, here is what I see

![image](https://github.com/hopfront/hopfront/assets/140622709/f3c1529c-08ce-4fa7-9fd9-57c7291ff349)

I can see in dev tools that the query to the API succeed

**Comment by AnthonyMde** [comment]
Hi, 

Can you give me the SystemInformation schema please?
Do you succeed to have responses on other endpoints or every endpoints seem to have the same problem?
Does the call succeeded with a 200?

Thanks.

**Comment by glb-cblin** [comment]
I have the same problem on all operations

The call succed with a 200 (I'm using the proxy)

![image](https://github.com/hopfront/hopfront/assets/140622709/3af3de6d-e827-4d6d-92c9-3e80a9044fa1)

![image](https://github.com/hopfront/hopfront/assets/140622709/983c6bac-9622-421b-b47a-1b87b95f6e9f)

    "SystemInformation": {
        "type": "object",
        "properties": {
          "environment": {
            "type": "string",
            "nullable": true
          },
          "reachfiveAuthenticationOptions": {
            "$ref": "#/components/schemas/ReachfiveAuthenticationOptions"
          },
          "version": {
            "$ref": "#/components/schemas/SystemVersion"
          }
        },
        "additionalProperties": false
      },
      "SystemVersion": {
        "type": "object",
        "properties": {
          "commit": {
            "type": "string",
            "nullable": true
          },
          "tag": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },

    "ReachfiveAuthenticationOptions": {
        "type": "object",
        "properties": {
          "issuer": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },

**Comment by AnthonyMde** [comment]
Schemas look good. In the proxy's response bodies you got the expected value as well?
If you encounter this issue in all your calls, are you sure that schemas are correctly located in "/components/schemas/" in the spec?
And that there is no duplicates (if there are two "/components" in the spec it will leads to errors).

**Comment by AnthonyMde** [comment]
It would be great if it's possible for you to send us your specification (or a relevant part of it) to our support email : support@hopfront.com.

Thank you for your time.

**Comment by AnthonyMde** [comment]
@glb-cblin do you have any news on this? I'll have to close this issue if no new elements are provided.

**Comment by glb-cblin** [comment]
I wont be able to provide new things because I reverted to postman for the moment ... sorry
